### ISSUE TITLE
Manifest is not getting detected. 

### ISSUE THREAD

**Issue by SujeevPachala** [almenscorner/Munki-Manifest-Generator#2]
I have my setup exactly you defined and sometimes the RunBook doesn't attach the manifest and I am not getting the site_default but my serial number. This is intermittent experience. 

<img width="1675" alt="Screen Shot 2022-10-14 at 7 44 53 PM" src="https://user-images.githubusercontent.com/113067854/195897868-720ce6dd-b563-4352-a7d9-054d02d035c0.png">

**Comment by almenscorner** [comment]
Hi,

The way I would set this up is to add all common applications that is not assigned to a specific group of macs to the "site_default" manifest. I also advise to not configure catalogs on the manifests you specify here and instead let the tool configure the catalog on the specific device manifest. I also see no reason why site_default should include an included manifest as that targets all devices by default.

This is a great guide to Munki and manifests: https://groob.io/posts/manifest-guide/

**Comment by SujeevPachala** [comment]
Thanks for all your help in guiding, your articles are amazing and looking forward to try your DevOps method. 

![Tobias](https://user-images.githubusercontent.com/113067854/197249235-0d61741f-5d88-434c-b149-fc113ec1479e.jpeg)
