### ISSUE TITLE
catalogs = ["Production"]

### ISSUE THREAD

**Issue by ChristianJucker** [almenscorner/Munki-Manifest-Generator#4]
Hi,

sorry, quick question, in my case the catalog production is always added even if it doesn't exist in my Repo. is this in purpose ?

i see these lines
if add_catalogs:
        catalogs = ["Production"]

Christian

**Comment by almenscorner** [comment]
Hi,

Yes, the "Production" catalog is added by default as the standard catalog for apps to all manifests.

This is the default as most setups I've seen is using production, if there is a problem using the tool because of this I might change it however.

**Comment by ChristianJucker** [comment]
Hi Tobias,

thanks a lot for the quick reply  (actually I wanted to thank you for all your articles too.. they make the miserable life with intune much much better 😊)

I can live with it that way, my main issue was that my catalog was called production in lower case, this caused then havoc for the client… On the other hand I tend to always have groups for intune deployments and not use all users or all computers, therefore if you have some unexcepted free time an additional attribute for the job like “apply default catalog: true/false” and “default catalog name=”””. would help …

Gruss und Dank
Christian Jucker


From: Tobias Almén ***@***.***>
Date: Friday, 3 March 2023 at 07:21
To: almenscorner/Munki-Manifest-Generator ***@***.***>
Cc: Christian Jucker ***@***.***>, Author ***@***.***>
Subject: Re: [almenscorner/Munki-Manifest-Generator] catalogs = ["Production"] (Issue #4)

Hi,

Yes, the "Production" catalog is added by default as the standard catalog for apps to all manifests.

This is the default as most setups I've seen is using production, if there is a problem using the tool because of this I might change it however.

**Comment by almenscorner** [comment]
Thank you very much ☺️

Ah I see, you have a good point. What I will do is add an argument for "default catalog", if set it will override "Production", if not set the default as it is today will be used instead. I think I will be able to get that into the tool quick as it is not a huge change :)

**Comment by ChristianJucker** [comment]
Ok. Sounds very good.. thanks!

Gruss und Dank
Christian Jucker


From: Tobias Almén ***@***.***>
Date: Friday, 3 March 2023 at 08:26
To: almenscorner/Munki-Manifest-Generator ***@***.***>
Cc: Christian Jucker ***@***.***>, Author ***@***.***>
Subject: Re: [almenscorner/Munki-Manifest-Generator] catalogs = ["Production"] (Issue #4)

Thank you very much ☺️

Ah I see, you have a good point. What I will do is add an argument for "default catalog", if set it will override "Production", if not set the default as it is today will be used instead. I think I will be able to get that into the tool quick as it is not a huge change :)

**Comment by almenscorner** [comment]
Default catalog option has been added in v1.1.2, details can be found on the releases page.

**Comment by ChristianJucker** [comment]
Cool… works very good.. thanks for the quick fix and a nice WE

Christian


From: Tobias Almén ***@***.***>
Date: Friday, 3 March 2023 at 14:14
To: almenscorner/Munki-Manifest-Generator ***@***.***>
Cc: Christian Jucker ***@***.***>, Author ***@***.***>
Subject: Re: [almenscorner/Munki-Manifest-Generator] catalogs = ["Production"] (Issue #4)

Default catalog option has been added in v1.1.2, details can be found on the releases page.
